# Site
title: BioLiloLab
subtitle: Bioprototipagem com prop√≥sito

# URL
url: http://
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4442
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
